const TASK_SATUS = {
  TODO: 'TODO',
  IN_PROGRESS: 'IN PROGRESS',
  COMPLETED: 'COMPLETED',
};

const USER_VERIFICATION_STATUS = {
  NONE: 'NONE',
  WAITING: 'WAITING',
  VERIFIED: 'VERIFIED',
  REJECTED: 'REJECTED',
};

export {TASK_SATUS, USER_VERIFICATION_STATUS};
